PruebaQ10Web/PruebaQ10Web/Models/Subject.cs
namespace PruebaQ10Web.Models
{
    public class Subject
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int Credits { get; set; }
    }

    public class SubjectRequest
    {
        public string Name { get; set; }
        public string Code { get; set; }
        public int Credits { get; set; }
    }
}

PruebaQ10Web/PruebaQ10Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace PruebaQ10Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

PruebaQ10Web/PruebaQ10Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PruebaQ10Web.Models;
using System.Reflection.Metadata;
using System.Text;
using System.Text.Json;

namespace PruebaQ10Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IHttpClientFactory _httpClientFactory;
        public IndexModel(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public int StudentEditId = 0;
        public bool NewStudent = false;
        public GeneralResponse<Student[]> GetAllStudents = new();
        public Student[] Students { get; set; } = [];

        public async Task OnGetAsync()
        {
            var client = _httpClientFactory.CreateClient("ApiClient");

            var response = await client.GetAsync("student");

            if (response.IsSuccessStatusCode)
            {
                var json = await response.Content.ReadAsStringAsync();
                GetAllStudents = JsonSerializer.Deserialize<GeneralResponse<Student[]>>(json, new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                }) ?? new();

                Students = GetAllStudents.Data;
            }
        }

        public async Task<IActionResult> OnPostEditStudentAsync(int id)
        {
            StudentEditId = id;

            await OnGetAsync();

            // Hacer algo con el estudiante
            return Page();
        }

        public async Task<IActionResult> OnPostCancelEditStudentAsync(int id)
        {
            StudentEditId = 0;

            await OnGetAsync();

            // Hacer algo con el estudiante
            return Page();
        }

        public async Task<IActionResult> OnPostAddStudentAsync(int id)
        {
            NewStudent = true;

            await OnGetAsync();

            // Hacer algo con el estudiante
            return Page();
        }

        public async Task<IActionResult> OnPostCancelAddStudentAsync(int id)
        {
            NewStudent = false;

            await OnGetAsync();

            // Hacer algo con el estudiante
            return Page();
        }

        public async Task<IActionResult> OnPostSaveEditStudentAsync(int id, string FirstnameEditStudent, string LastnameEditStudent, int DocumentEditStudent, string EmailEditStudent)
        {
            var client = _httpClientFactory.CreateClient("ApiClient");

            var JsonEditStudent = JsonSerializer.Serialize(new StudentRequest
            {
                FirstName = FirstnameEditStudent,
                LastName = LastnameEditStudent,
                Document = DocumentEditStudent.ToString(),
                Email = EmailEditStudent
            });
            var content = new StringContent(JsonEditStudent, Encoding.UTF8, "application/json");

            var response = await client.PutAsync($"Student?updateStudentId={id}", content);

            if (response.IsSuccessStatusCode)
            {
                var json = await response.Content.ReadAsStringAsync();
                GeneralResponse<Student> SaveEditStudent = JsonSerializer.Deserialize<GeneralResponse<Student>>(json, new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                }) ?? new();

                if (SaveEditStudent.Success)
                {
                    StudentEditId = 0;
                    await OnGetAsync();
                }
            }

            // Hacer algo con el estudiante
            return Page();
        }

        public async Task<IActionResult> OnPostSaveNewStudentAsync(string FirstnameNewStudent, string LastnameNewStudent, int DocumentNewStudent, string EmailNewStudent)
        {
            var client = _httpClientFactory.CreateClient("ApiClient");

            var JsonEditStudent = JsonSerializer.Serialize(new StudentRequest
            {
                FirstName = FirstnameNewStudent,
                LastName = LastnameNewStudent,
                Document = DocumentNewStudent.ToString(),
                Email = EmailNewStudent
            });
            var content = new StringContent(JsonEditStudent, Encoding.UTF8, "application/json");

            var response = await client.PostAsync($"Student", content);

            if (response.IsSuccessStatusCode)
            {
                var json = await response.Content.ReadAsStringAsync();
                GeneralResponse<Student> SaveNewStudent = JsonSerializer.Deserialize<GeneralResponse<Student>>(json, new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                }) ?? new();

                if (SaveNewStudent.Success)
                {
                    StudentEditId = 0;
                    await OnGetAsync();
                }
            }

            // Hacer algo con el estudiante
            return Page();
        }

        public async Task<IActionResult> OnPostRemoveStudentAsync(int id)
        {
            var client = _httpClientFactory.CreateClient("ApiClient");

            var response = await client.DeleteAsync($"Student?removeStudentId={id}");

            if (response.IsSuccessStatusCode)
            {
                var json = await response.Content.ReadAsStringAsync();
                GeneralResponse<int> RemoveStudent = JsonSerializer.Deserialize<GeneralResponse<int>>(json, new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                }) ?? new();

                if (RemoveStudent.Success)
                {
                    StudentEditId = 0;
                    await OnGetAsync();
                }
            }

            // Hacer algo con el estudiante
            return Page();
        }
    }
}

PruebaQ10Web/PruebaQ10Web/Pages/Registration.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PruebaQ10Web.Pages
{
    public class RegistrationModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

PruebaQ10Web/PruebaQ10Web/Pages/Subject.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PruebaQ10Web.Models;
using System.Text;
using System.Text.Json;

namespace PruebaQ10Web.Pages
{
    public class SubjectModel : PageModel
    {
        private readonly IHttpClientFactory _httpClientFactory;
        public SubjectModel(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public int SubjectEditId = 0;
        public bool NewSubject = false;

        public GeneralResponse<Subject[]> GetAllSubject = new();
        public Subject[] Subjects { get; set; } = [];

        public async Task OnGetAsync()
        {
            var client = _httpClientFactory.CreateClient("ApiClient");

            var response = await client.GetAsync("subject");

            if (response.IsSuccessStatusCode)
            {
                var json = await response.Content.ReadAsStringAsync();
                GetAllSubject = JsonSerializer.Deserialize<GeneralResponse<Subject[]>>(json, new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                }) ?? new();

                Subjects = GetAllSubject.Data;
            }
        }

        public async Task<IActionResult> OnPostEditSubjectAsync(int id)
        {
            SubjectEditId = id;

            await OnGetAsync();

            // Hacer algo con el estudiante
            return Page();
        }

        public async Task<IActionResult> OnPostCancelEditSubjectAsync(int id)
        {
            SubjectEditId = 0;

            await OnGetAsync();

            // Hacer algo con el estudiante
            return Page();
        }

        public async Task<IActionResult> OnPostAddSubjectAsync(int id)
        {
            NewSubject = true;

            await OnGetAsync();

            // Hacer algo con el estudiante
            return Page();
        }

        public async Task<IActionResult> OnPostCancelAddSubjectAsync(int id)
        {
            NewSubject = false;

            await OnGetAsync();

            // Hacer algo con el estudiante
            return Page();
        }

        public async Task<IActionResult> OnPostSaveEditSubjectAsync(int id, string NameEditSubject, string CodeEditSubject, int CreditsEditSubject)
        {
            var client = _httpClientFactory.CreateClient("ApiClient");

            var JsonEditSubject = JsonSerializer.Serialize(new SubjectRequest
            {
                Name = NameEditSubject,
                Code = CodeEditSubject,
                Credits = CreditsEditSubject
            });
            var content = new StringContent(JsonEditSubject, Encoding.UTF8, "application/json");

            var response = await client.PutAsync($"Subject?updateSubjectId={id}", content);

            if (response.IsSuccessStatusCode)
            {
                var json = await response.Content.ReadAsStringAsync();
                GeneralResponse<Subject> SaveEditSubject = JsonSerializer.Deserialize<GeneralResponse<Subject>>(json, new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                }) ?? new();

                if (SaveEditSubject.Success)
                {
                    SubjectEditId = 0;
                    await OnGetAsync();
                }
            }

            // Hacer algo con el estudiante
            return Page();
        }

        public async Task<IActionResult> OnPostSaveNewSubjectAsync(string NameNewSubject, string CodeNewSubject, int CreditsNewSubject)
        {
            var client = _httpClientFactory.CreateClient("ApiClient");

            var JsonEditSubject = JsonSerializer.Serialize(new SubjectRequest
            {
                Name = NameNewSubject,
                Code = CodeNewSubject,
                Credits = CreditsNewSubject
            });
            var content = new StringContent(JsonEditSubject, Encoding.UTF8, "application/json");

            var response = await client.PostAsync($"Subject", content);

            if (response.IsSuccessStatusCode)
            {
                var json = await response.Content.ReadAsStringAsync();
                GeneralResponse<Subject> SaveNewSubject = JsonSerializer.Deserialize<GeneralResponse<Subject>>(json, new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                }) ?? new();

                if (SaveNewSubject.Success)
                {
                    SubjectEditId = 0;
                    await OnGetAsync();
                }
            }

            // Hacer algo con el estudiante
            return Page();
        }

        public async Task<IActionResult> OnPostRemoveSubjectAsync(int id)
        {
            var client = _httpClientFactory.CreateClient("ApiClient");

            var response = await client.DeleteAsync($"Subject?removeSubjectId={id}");

            if (response.IsSuccessStatusCode)
            {
                var json = await response.Content.ReadAsStringAsync();
                GeneralResponse<int> RemoveSubject = JsonSerializer.Deserialize<GeneralResponse<int>>(json, new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                }) ?? new();

                if (RemoveSubject.Success)
                {
                    SubjectEditId = 0;
                    await OnGetAsync();
                }
            }

            // Hacer algo con el estudiante
            return Page();
        }
    }
}

PruebaQ10Web/PruebaQ10Web/Pages/Index.cshtml
@page
@model IndexModel

<div class="container">
    <form method="post">
        <div class="row justify-content-between">
            <div class="col-md">
                <h2>Estudiantes</h2>
            </div>
            <div class="col-md">
                <div class="row justify-content-end w-100 gap-1">
                    <button type="submit" class="btn btn-outline-primary btn-sm w-auto" name="NewStudent" asp-page-handler="AddStudent">Nuevo</button>
                </div>
            </div>
        </div>
    </form>
</div>

@if (Model.Students.Length == 0)
{
    <p>No hay estudiantes registrados.</p>
}
else
{
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Apellido</th>
                <th scope="col">Documento</th>
                <th scope="col">Correo electronico</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.NewStudent)
            {
                <form method="post">
                <tr>
                    <td>
                        <input type="text" class="form-control" placeholder="Nombre" aria-label="Nombre" name="FirstnameNewStudent" aria-describedby="basic-addon1">
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Apellido" aria-label="Apellido" name="LastnameNewStudent" aria-describedby="basic-addon1">
                    </td>
                    <td>
                        <input type="number" class="form-control" placeholder="Documento" aria-label="Documento" name="DocumentNewStudent" aria-describedby="basic-addon1">
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Email" aria-label="Email" name="EmailNewStudent" aria-describedby="basic-addon1">
                    </td>
                    <td>
                        <div class="row justify-content-end w-100 gap-1">
                            <button type="submit" class="btn btn-outline-success btn-sm w-auto" name="Id" asp-page-handler="SaveNewStudent">Guardar</button>
                            <button type="submit" class="btn btn-outline-danger btn-sm w-auto" name="Id" asp-page-handler="CancelAddStudent">Cancelar</button>
                        </div>
                    </td>
                </tr>
                </form>
            }
            @foreach (var student in Model.Students)
            {
                @if (@student.Id == Model.StudentEditId)
                {
                    <form method="post">
                    <tr>
                        <td>
                            <input type="text" class="form-control" placeholder="Nombre" aria-label="Nombre" aria-describedby="basic-addon1" name="FirstnameEditStudent" value="@student.FirstName">
                        </td>
                        <td>
                            <input type="text" class="form-control" placeholder="Apellido" aria-label="Apellido" aria-describedby="basic-addon1" name="LastnameEditStudent" value="@student.LastName">
                        </td>
                        <td>
                            <input type="number" class="form-control" placeholder="Documento" aria-label="Documento" aria-describedby="basic-addon1" name="DocumentEditStudent" value="@student.Document">
                        </td>
                        <td>
                            <input type="text" class="form-control" placeholder="Email" aria-label="Email" aria-describedby="basic-addon1" name="EmailEditStudent" value="@student.Email">
                        </td>
                        <td>
                            <div class="row justify-content-end w-100 gap-1">
                                <button type="submit" class="btn btn-outline-success btn-sm w-auto" name="Id" asp-page-handler="SaveEditStudent" value="@student.Id">Guardar</button>
                                <button type="submit" class="btn btn-outline-danger btn-sm w-auto" name="Id" asp-page-handler="CancelEditStudent" value="@student.Id">Cancelar</button>
                            </div>
                        </td>
                    </tr>
                    </form>
                }
                else
                {
                    <form method="post">
                    <tr>
                        <td>@student.FirstName</td>
                        <td>@student.LastName</td>
                        <td>@student.Document</td>
                        <td>@student.Email</td>
                        <td>
                            <div class="row justify-content-end w-100 gap-1">
                                <button type="submit" class="btn btn-outline-warning btn-sm w-auto" name="Id" asp-page-handler="EditStudent" value="@student.Id">Editar</button>
                                <button type="submit" class="btn btn-outline-danger btn-sm w-auto" name="Id" asp-page-handler="RemoveStudent" value="@student.Id">Eliminar</button>
                            </div>
                        </td>
                    </tr>
                    </form>
                }
            }
        </tbody>
    </table>
}

PruebaQ10Web/PruebaQ10Web/Pages/Registration.cshtml
@page
@model PruebaQ10Web.Pages.RegistrationModel
@{
}

PruebaQ10Web/PruebaQ10Web/Pages/Subject.cshtml
@page
@model SubjectModel

<div class="container">
    <form method="post">
        <div class="row justify-content-between">
            <div class="col-md">
                <h2>Materias</h2>
            </div>
            <div class="col-md">
                <div class="row justify-content-end w-100 gap-1">
                    <button type="submit" class="btn btn-outline-primary btn-sm w-auto" name="NewSubject" asp-page-handler="AddSubject">Nuevo</button>
                </div>
            </div>
        </div>
    </form>
</div>

@if (Model.Subjects.Length == 0)
{
    <p>No hay materias registradas.</p>
}
else
{
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Codigo</th>
                <th scope="col">Creditos</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.NewSubject)
            {
                <form method="post">
                <tr>
                    <td>
                        <input type="text" class="form-control" placeholder="Nombre" aria-label="Nombre" aria-describedby="basic-addon1" name="NameNewSubject">
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Codigo" aria-label="Codigo" aria-describedby="basic-addon1" name="CodeNewSubject">
                    </td>
                    <td>
                        <input type="number" class="form-control" placeholder="Creditos" aria-label="Creditos" aria-describedby="basic-addon1" name="CreditsNewSubject">
                    </td>
                    <td>
                        <div class="row justify-content-end w-100 gap-1">
                            <button type="submit" class="btn btn-outline-success btn-sm w-auto" name="Id" asp-page-handler="SaveNewSubject">Guardar</button>
                            <button type="submit" class="btn btn-outline-danger btn-sm w-auto" name="Id" asp-page-handler="CancelAddSubject">Cancelar</button>
                        </div>
                    </td>
                </tr>
                </form>
            }
            @foreach (var subject in Model.Subjects)
            {
                @if (@subject.Id == Model.SubjectEditId)
                {
                    <form method="post">
                    <tr>
                        <td>
                            <input type="text" class="form-control" placeholder="Nombre" aria-label="Nombre" aria-describedby="basic-addon1" name="NameEditSubject" value="@subject.Name">
                        </td>
                        <td>
                            <input type="text" class="form-control" placeholder="Codigo" aria-label="Codigo" aria-describedby="basic-addon1" name="CodeEditSubject" value="@subject.Code">
                        </td>
                        <td>
                            <input type="number" class="form-control" placeholder="Creditos" aria-label="Creditos" aria-describedby="basic-addon1" name="CreditsEditSubject" value="@subject.Credits">
                        </td>
                        <td>
                            <div class="row justify-content-end w-100 gap-1">
                                <button type="submit" class="btn btn-outline-success btn-sm w-auto" name="Id" asp-page-handler="SaveEditSubject" value="@subject.Id">Guardar</button>
                                <button type="submit" class="btn btn-outline-danger btn-sm w-auto" name="Id" asp-page-handler="CancelEditSubject" value="@subject.Id">Cancelar</button>
                            </div>
                        </td>
                    </tr>
                    </form>
                }
                else
                {
                    <form method="post">
                    <tr>
                        <td>@subject.Name</td>
                        <td>@subject.Code</td>
                        <td>@subject.Credits</td>
                        <td>
                            <div class="row justify-content-end w-100 gap-1">
                                <button type="submit" class="btn btn-outline-warning btn-sm w-auto" name="Id" asp-page-handler="EditSubject" value="@subject.Id">Editar</button>
                                <button type="submit" class="btn btn-outline-danger btn-sm w-auto" name="Id" asp-page-handler="RemoveSubject" value="@subject.Id">Eliminar</button>
                            </div>
                        </td>
                    </tr>
                    </form>
                }
            }
        </tbody>
    </table>
}